Bookstore: add reducers and actions
habasm/bookstore pull request #2
Opened 2023-02-28 06:53 UTC by habasm

### Reducers and actions of a bookstore project by @habasm 

### Objectives
- Understand the concept of state management.
- Use store, actions, and reducers in React.

### Actions
- Setup a Redux store
- Create a slice to save your state and reducers

2023-02-28 06:58 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @habasm,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### - Your README contains the Microverse logo. Kindly remove it as part of the customization requirement.
### - You should have a Future Features section listing one or more features you intend to implement in the future. Ensure there is a menu link for it as well.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-28 07:01 UTC, habasm commented
### @TedLivist thanks, now it's fixed.

2023-02-28 07:04 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @habasm,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You still do not have the "Future Features" section as pointed out. Kindly refer to [the template](https://github.com/microverseinc/readme-template) for guidance.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-28 07:27 UTC, habasm commented
@TedLivist Thanks again, I tried to fixed it also.

2023-02-28 08:28 UTC, FrederickMih requested changes
## Hi :raising_hand:  @habasm , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Linter checks passed :heavy_check_mark: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 08:28 UTC, FrederickMih commented on src/redux/books/books.js
> +export default bookReducer;
- [ ] Hi @habasm, once more, let's kindly adhere to the requirements of this project. Let's kindly import the necessary methods from Redux Toolkit as requested and define slice of state for books and categories. **Hints** `import { createSlice } from "@reduxjs/toolkit"` Next, you'll kindly Create an initialState with a state value books that contains an empty array. **Hints**
```
initialState: {
    books: [],
  }
```

- After creating two reducers addBook and removeBook export by default bookReducer.reducer. Reducers should be created inside:

```
export const bookReducer = createSlice({

})
```

- Kindly check the requirements once more below on the screenshot:

![image](https://user-images.githubusercontent.com/63087491/221787239-77526f62-5e28-4727-8f80-d85bc10595a9.png)

2023-02-28 08:28 UTC, FrederickMih commented on src/components/Categories/Categories.js
>  export default Categories;
- [ ] Kindly check the comment above :arrow_up:

2023-02-28 08:28 UTC, FrederickMih commented on README.md
- [**Optional**] @habasm your README.md file contains two project titles. Below and above table of content.
![Screenshot from 2023-02-28 09-25-50](https://user-images.githubusercontent.com/63087491/221796295-a07fc906-a5f3-4fad-9cf3-ec22559ef376.png)

2023-03-01 08:10 UTC, christianbiring1 approved these changes
Hi @habasm , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![nicee](https://user-images.githubusercontent.com/97100091/222080791-90048602-4c29-46e0-8454-df0c4b8fb228.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] The redux is set properly to manage the app state :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 08:16 UTC, merged